site_name: eagle-core

theme:
  name : "material"
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:

  - mkdocstrings
  - mermaid2:
      version: 10.6.1
      arguments:
          theme: |
            ^(JSON.parse(__md_get("__palette").index == 1)) ? 'dark' : 'light'
      

  - mkdocs-jupyter
  #     include: ["tests/*.ipynb"]

markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  # - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - tables
  # - pymdownx.superfences:
  #     # make exceptions to highlighting of code:
  #     custom_fences:
  #       - name: mermaid
  #         class: mermaid
  #         format: !!python/name:mermaid2.fence_mermaid
  


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # - extra/refresh_on_toggle_dark_light.js
  - javascripts/mermaid-refresh-theme.js


# extra_javascript:
#   - javascripts/katex.js 
#   - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
#   - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

# extra_css:
#   - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

nav:
  - Presentation: README.md

  - 'Package' :
    - 'Filters' :
      - 'Linear' : Eaglecore/Filters/Linear.md
      - 'No linear' : Eaglecore/Filters/NoLinear.md
    - 'Differential' : Eaglecore/Differential.md
    - 'Signal' :
      - 'Measure' : Eaglecore/Signal/Measure.md
      - 'Processing' : Eaglecore/Signal/Processing.md
    - 'IO (Input/Output)' : Eaglecore/Io.md
    - 'Metrics' : Eaglecore/Metrics.md
    - 'Noise' : Eaglecore/Noise.md
    - 'Point Spread Functions (PSF)' : Eaglecore/Psf.md
    - 'Thresholding' : Eaglecore/Thresholding.md
    - 'Types' : Eaglecore/Types.md
    - 'Utils' : Eaglecore/Utils.md

  - 'Notebooks' :
    - 'Differential' : Notebooks/differential.ipynb
    - 'Noise' : Notebooks/noise.ipynb
    - 'Signal' :
      - 'Measure' : Notebooks/Signal/measure.ipynb
    - 'Thresholding' : Notebooks/thresholding.ipynb
    - 'Types' : Notebooks/types.ipynb

  # - reference.md