site_name: eaglecore

theme:
  # name : "material"
  name: "readthedocs"

plugins:
  - mkdocstrings

nav:
  - Presentation: index.md

  - 'Eaglecore' :
    - 'Filters' :
      - 'Linear' : Eaglecore/Filters/Linear.md

  # - reference.md
